language: R
sudo: false
cache: packages

notifications:
  email:
  - alexadner.lange@uni-goettingen.de

addons:
  apt:
    update: true
    packages:
      - libgsl-dev
      - qpdf
      - ghostscript


script:
  - |
    R CMD build . --compact-vignettes=both
  - |
    R CMD check *tar.gz --as-cran
  - |
    R CMD build .
    travis_wait 100 R CMD check *tar.gz

